### ISSUE TITLE
2020_11_23: New-FileExt

### ISSUE THREAD

**Issue by lucexa** [dannyroemhild/ransomware-fileext-list#19]
**Week in Ransomware 2020_11_20:**

*.vvoa
*.ZqVIkE
*.honor
*.epor
*.LIZARD 
*.ELDAOLSA
*.joker
*.dex
*.sss 
*.zimba
.TG33
.r2block 
 .ZIN
.pulpit
.sglh
.esexz
.SWP
.cvc

**Comment by dannyroemhild** [comment]
added New Fileextensions

*.ZqVIkE
*.epor
*.LIZARD
*.ELDAOLSA
*.joker
*.dex
*.sss
*.r2block
*.ZIN
*.pulpit
*.sglh
*.esexz
*.SWP
*.cvc
