### ISSUE TITLE
20210208: New File Extentions

### ISSUE THREAD

**Issue by lucexa** [dannyroemhild/ransomware-fileext-list#21]
Here the Exentions of the newest BleepingComputer Article
https://www.bleepingcomputer.com/news/security/the-week-in-ransomware-february-5th-2021-data-destruction/

*.plam
*.cosd 
*.lucifer
*.DERZKO
*.MILIHPEN
.omfl

**Comment by dannyroemhild** [comment]
Resolved with #22
