### ISSUE TITLE
20210308 New-FileExtentions

### ISSUE THREAD

**Issue by lucexa** [dannyroemhild/ransomware-fileext-list#24]
Bleeping Computer Article: https://www.bleepingcomputer.com/news/security/the-week-in-ransomware-march-5th-2021-targeting-service-providers/

*.oral 
*.urs
*.ribd
*.systems32x
*.RansomTrojanLock
*.IQ_IQ

**Comment by dannyroemhild** [comment]
Done with https://github.com/dannyroemhild/ransomware-fileext-list/commit/58ec482cd0c28ae85eb765996a59beff746aaa91
