### ISSUE TITLE
20210329 New-FileExtentions

### ISSUE THREAD

**Issue by lucexa** [dannyroemhild/ransomware-fileext-list#25]
https://www.bleepingcomputer.com/news/security/the-week-in-ransomware-march-26th-2021-attacks-increase/

*.aes
*.bqd2
*.pecunia
*.ekvf
*.HANTA

**Comment by dannyroemhild** [comment]
Done with https://github.com/dannyroemhild/ransomware-fileext-list/commit/58ec482cd0c28ae85eb765996a59beff746aaa91
