### ISSUE TITLE
20200510: New Extentions

### ISSUE THREAD

**Issue by lucexa** [dannyroemhild/ransomware-fileext-list#26]
Bleeping Computer:
https://www.bleepingcomputer.com/news/security/the-week-in-ransomware-may-7th-2021-attacking-healthcare/

*.henry217
*.saverswasted
*.rejg
*.GoNNaCry

**Comment by dannyroemhild** [comment]
Fixed with https://github.com/dannyroemhild/ransomware-fileext-list/releases/tag/1.0.28
