### ISSUE TITLE
tag 1.1.26 instead of 1.1.27 marked as latest release

### ISSUE THREAD

**Issue by u1b4n** [dannyroemhild/ransomware-fileext-list#33]
**Is there a reason why the 1.1.27 tag is not marked as latest?** 
I regularly fetch the latest release. Today I was wondering why I still hadn't heard of any new release from your repo.
![image](https://github.com/dannyroemhild/ransomware-fileext-list/assets/123732252/bfd2cdc5-05fb-4250-a536-3183d6332891)

Currently release 1.1.26 is marked as latest release.
![image](https://github.com/dannyroemhild/ransomware-fileext-list/assets/123732252/d04c410b-2c18-4c3c-8c06-7c9c8c03f2e8)

Your repo has been incredibly helpful to me. Keep up the excellent work! 🚀
And thanks for the your answer beforehand.

**Comment by dannyroemhild** [comment]
Hi, thanks for the Kind words and the notice about the latest Release issue. It ist fixed Now.
