### ISSUE TITLE
Is the repository still maintained?

### ISSUE THREAD

**Issue by u1b4n** [dannyroemhild/ransomware-fileext-list#34]
Hi dannyroemhild,

I hope you're doing well. I noticed there haven't been updates to the repo for the past three months. Will there be updates soon, or is there a change in plans? Your response would be appreciated.

Thanks,
urban

**Comment by dannyroemhild** [comment]
Hi, thanks for your question.

The Last months I wasn't able to Update the repo - but i try to do a Big Update in the next days.

Thanks for using the repo.

Kindest Regards
